### ISSUE TITLE
Questions about the rich-club analysis

### ISSUE THREAD

**Issue by yutinghe99** [markett-lab/AlzheimerRichClub#1]
Hi, experts

I have read your paper, it's an interesting work. And thank you for making your code public. I would also like to do rich-club analysis on my own dataset,  as a beginner, your article and code help me greatly.

However, I still have some confusion, I would appreciate it if you could guide me:
1. It looks like your rich club analysis was based on the group-averaged matrix. I have two groups, patients and controls, and I'd like to compare the rich-club coefficient between them, do I need to generate a group-averaged matrix for each group, respectively? And then run the _b_rc_analysis.m_ for each group-averaged matrix?
2. I would like to know what exactly the _radj_ you load in _b_rc_analysis.m_ looks like? Is it just an empty 3D matrix?
![image](https://github.com/markett-lab/AlzheimerRichClub/assets/137074150/eec9ee10-9a9c-4e24-b564-f7a78450a923)

Best regards,
Yuting

**Comment by markett-lab** [comment]
Hi Yuting,
I am happy you find the code useful.

1. Most likely, you would want to run this analysis for each participant and then compare the two groups. This is a bit different from the approach we did here, but works better when you are interested in individual rich clubs and/or group differences. Would be similar to this approach: https://onlinelibrary.wiley.com/doi/10.1002/hbm.25950 Depending on your research question, you may want to look at the area under the normalized rich club curve as the key dependent measure?
2. This is the null model. In this case, we used BCT's randmio to create several thousand random networks from the empirical matrix. radj is thus a three dimensional matrix with nodes * nodes along the first two dimensions and the randomizaitions along the third. 
Hope this helps?
Sebastian

**Comment by yutinghe99** [comment]
Hi Sebastian,

Thank you for your prompt response. I have looked at your attached paper above, it is more similar to my goal.

Once again thank you for your help.

Best regards,
Yuting
